-- Seed: Email templates for automation events (inline CSS only, email-client friendly)

INSERT INTO email_templates (template_key, display_name, subject_template, html_template, is_active)
VALUES
(
  'request_confirmation',
  'Anfragebestaetigung (Kundin/Kunde)',
  'Wir haben deine Anfrage erhalten - {{system.site_name}}',
  '<!doctype html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:24px;background:#f5f5f4;font-family:Arial,Helvetica,sans-serif;color:#1c1917;"><table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%"><tr><td align="center"><table role="presentation" cellspacing="0" cellpadding="0" border="0" width="680" style="max-width:680px;background:#ffffff;border:1px solid #e7e5e4;border-radius:14px;overflow:hidden;"><tr><td style="padding:28px 32px 14px 32px;border-bottom:1px solid #e7e5e4;"><div style="font-size:11px;letter-spacing:1.8px;text-transform:uppercase;color:#0f766e;font-weight:bold;">{{system.site_name}}</div><h1 style="margin:10px 0 8px 0;font-size:26px;line-height:1.25;color:#1c1917;">Danke für deine Anfrage</h1><p style="margin:0;font-size:14px;line-height:1.6;color:#57534e;">Hallo {{client.first_name}} {{client.last_name}}, wir haben deine Anfrage erfolgreich erhalten.</p></td></tr><tr><td style="padding:24px 32px;"><div style="background:#fafaf9;border:1px solid #e7e5e4;border-radius:10px;padding:16px;"><div style="font-size:12px;line-height:1.4;font-weight:bold;text-transform:uppercase;letter-spacing:0.6px;color:#44403c;">Anfragedetails</div><p style="margin:10px 0 0 0;font-size:14px;line-height:1.6;"><strong>Service:</strong> {{request.service_slug}}</p><p style="margin:4px 0 0 0;font-size:14px;line-height:1.6;"><strong>Gewünschteer Termin:</strong> {{request.desired_at}}</p><p style="margin:4px 0 0 0;font-size:14px;line-height:1.6;"><strong>Kontaktweg:</strong> {{request.contact_preference}}</p><p style="margin:4px 0 0 0;font-size:14px;line-height:1.6;"><strong>Notizen:</strong> {{request.notes}}</p></div><p style="margin:18px 0 0 0;font-size:14px;line-height:1.7;color:#44403c;">Wir melden uns zeitnah mit einem Terminvorschlag bei dir.</p></td></tr><tr><td style="padding:14px 32px;background:#fafaf9;border-top:1px solid #e7e5e4;font-size:12px;line-height:1.5;color:#78716c;">Support: {{system.support_email}} | Kontakt: {{system.contact_email}}</td></tr></table></td></tr></table></body></html>',
  1
),
(
  'admin_request_info',
  'Deine Rechnung ist da',
  '<!doctype html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:24px;background:#f4f4f5;font-family:Arial,Helvetica,sans-serif;color:#18181b;"><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="640" style="max-width:640px;background:#ffffff;border:1px solid #e4e4e7;border-radius:14px;overflow:hidden;"><tr><td style="padding:26px 30px;border-bottom:1px solid #e4e4e7;"><h1 style="margin:0 0 10px 0;font-size:26px;line-height:1.25;color:#18181b;">Deine Rechnung</h1><p style="margin:0;font-size:14px;line-height:1.6;color:#3f3f46;">Hallo {{client.first_name}}, deine Rechnung wurde erstellt.</p></td></tr><tr><td style="padding:20px 30px;"><p style="margin:0 0 10px 0;font-size:14px;line-height:1.6;color:#3f3f46;">Die Rechnung findest du als PDF-Anhang in dieser E-Mail.</p><p style="margin:0;font-size:14px;line-height:1.6;color:#3f3f46;">Bei Fragen antworte gerne direkt auf diese Nachricht.</p></td></tr><tr><td style="padding:12px 30px;background:#fafafa;border-top:1px solid #e4e4e7;font-size:12px;color:#71717a;">{{system.site_name}} | {{system.contact_email}}</td></tr></table></td></tr></table></body></html>',
  '<!doctype html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:24px;background:#f1f5f9;font-family:Arial,Helvetica,sans-serif;color:#0f172a;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td align="center"><table role="presentation" width="680" style="max-width:680px;background:#ffffff;border:1px solid #dbe3ec;border-radius:14px;overflow:hidden;"><tr><td style="padding:26px 32px 14px 32px;border-bottom:1px solid #e2e8f0;"><div style="font-size:11px;letter-spacing:1.8px;text-transform:uppercase;color:#3730a3;font-weight:bold;">Admin Notification</div><h1 style="margin:10px 0 8px 0;font-size:26px;line-height:1.25;color:#0f172a;">Neue Anfrage</h1><p style="margin:0;font-size:14px;line-height:1.6;color:#475569;">Eine neue Anfrage wurde ueber das Formular eingereicht.</p></td></tr><tr><td style="padding:22px 32px;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td valign="top" width="50%" style="padding-right:8px;"><div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:14px;"><div style="font-size:14px;font-weight:bold;color:#0f172a;">Kundendaten</div><p style="margin:10px 0 0 0;font-size:14px;line-height:1.6;color:#334155;">{{client.first_name}} {{client.last_name}}<br>{{client.email}}<br>{{client.phone}}</p></div></td><td valign="top" width="50%" style="padding-left:8px;"><div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:14px;"><div style="font-size:14px;font-weight:bold;color:#0f172a;">Anfrage</div><p style="margin:10px 0 0 0;font-size:14px;line-height:1.6;color:#334155;">Service: {{request.service_slug}}<br>Termin: {{request.desired_at}}<br>Status: {{request.status}}</p></div></td></tr></table></td></tr><tr><td style="padding:14px 32px;background:#f8fafc;border-top:1px solid #e2e8f0;font-size:12px;line-height:1.5;color:#64748b;">Generiert: {{system.generated_at}}</td></tr></table></td></tr></table></body></html>',
  1
),
(
  'appointment_accepted',
  'Terminvorschlag angenommen',
  '<!doctype html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:24px;background:#f1f5f9;font-family:Arial,Helvetica,sans-serif;color:#0f172a;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td align="center"><table role="presentation" width="680" style="max-width:680px;background:#ffffff;border:1px solid #dbe3ec;border-radius:14px;overflow:hidden;"><tr><td style="padding:26px 32px 14px 32px;border-bottom:1px solid #e2e8f0;"><div style="font-size:11px;letter-spacing:1.8px;text-transform:uppercase;color:#3730a3;font-weight:bold;">Admin Notification</div><h1 style="margin:10px 0 8px 0;font-size:26px;line-height:1.25;color:#0f172a;">Neue Anfrage</h1><p style="margin:0;font-size:14px;line-height:1.6;color:#475569;">Eine neue Anfrage wurde ueber das Formular eingereicht.</p></td></tr><tr><td style="padding:22px 32px;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td valign="top" width="50%" style="padding-right:8px;"><div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:14px;"><div style="font-size:14px;font-weight:bold;color:#0f172a;">Kundendaten</div><p style="margin:10px 0 0 0;font-size:14px;line-height:1.6;color:#334155;">{{client.first_name}} {{client.last_name}}<br>{{client.email}}<br>{{client.phone}}</p></div></td><td valign="top" width="50%" style="padding-left:8px;"><div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:14px;"><div style="font-size:14px;font-weight:bold;color:#0f172a;">Anfrage</div><p style="margin:10px 0 8px 0;font-size:14px;line-height:1.6;color:#334155;"><strong>Anfrageart:</strong> {{request.type_label}}</p>{{request.admin_details_html}}</div></td></tr></table></td></tr><tr><td style="padding:14px 32px;background:#f8fafc;border-top:1px solid #e2e8f0;font-size:12px;line-height:1.5;color:#64748b;">Generiert: {{system.generated_at}}</td></tr></table></td></tr></table></body></html>',
  '<!doctype html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:24px;background:#ecfdf5;font-family:Arial,Helvetica,sans-serif;color:#14532d;"><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="640" style="max-width:640px;background:#ffffff;border:1px solid #a7f3d0;border-radius:14px;overflow:hidden;"><tr><td style="padding:26px 30px;"><h1 style="margin:0 0 10px 0;font-size:26px;line-height:1.25;color:#14532d;">Termin bestaetigt</h1><p style="margin:0 0 14px 0;font-size:14px;line-height:1.6;color:#14532d;">Hallo {{client.first_name}}, dein Termin wurde angenommen.</p><div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:10px;padding:14px;font-size:14px;line-height:1.7;color:#14532d;"><strong>Termin:</strong> {{booking.scheduled_at}}<br><strong>Status:</strong> {{booking.status}}</div></td></tr><tr><td style="padding:12px 30px;background:#f0fdf4;border-top:1px solid #bbf7d0;font-size:12px;color:#166534;">{{system.site_name}} | {{system.contact_email}}</td></tr></table></td></tr></table></body></html>',
  1
),
(
  'appointment_rejected',
  'Terminvorschlag abgelehnt',
  'Dein Terminvorschlag wurde abgelehnt',
  '<!doctype html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:24px;background:#fffbeb;font-family:Arial,Helvetica,sans-serif;color:#78350f;"><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="640" style="max-width:640px;background:#ffffff;border:1px solid #fde68a;border-radius:14px;overflow:hidden;"><tr><td style="padding:26px 30px;"><h1 style="margin:0 0 10px 0;font-size:26px;line-height:1.25;color:#92400e;">Termin aktuell nicht moeglich</h1><p style="margin:0 0 10px 0;font-size:14px;line-height:1.6;color:#78350f;">Hallo {{client.first_name}}, der vorgeschlagene Termin konnte leider nicht angenommen werden.</p><p style="margin:0;font-size:14px;line-height:1.6;color:#78350f;">Wir melden uns mit einer Alternative.</p></td></tr><tr><td style="padding:12px 30px;background:#fffbeb;border-top:1px solid #fde68a;font-size:12px;color:#92400e;">{{system.support_email}}</td></tr></table></td></tr></table></body></html>',
  1
),
(
  'appointment_cancelled',
  'Termin storniert',
  'Dein Termin wurde storniert',
  '<!doctype html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:24px;background:#fff1f2;font-family:Arial,Helvetica,sans-serif;color:#881337;"><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="640" style="max-width:640px;background:#ffffff;border:1px solid #fecdd3;border-radius:14px;overflow:hidden;"><tr><td style="padding:26px 30px;"><h1 style="margin:0 0 10px 0;font-size:26px;line-height:1.25;color:#9f1239;">Termin storniert</h1><p style="margin:0 0 14px 0;font-size:14px;line-height:1.6;color:#881337;">Hallo {{client.first_name}}, dein Termin wurde storniert.</p><div style="background:#fff1f2;border:1px solid #fecdd3;border-radius:10px;padding:14px;font-size:14px;line-height:1.7;color:#881337;"><strong>Termin:</strong> {{booking.scheduled_at}}<br><strong>Grund:</strong> {{booking.cancellation_reason}}</div></td></tr><tr><td style="padding:12px 30px;background:#fff1f2;border-top:1px solid #fecdd3;font-size:12px;color:#9f1239;">{{system.contact_email}}</td></tr></table></td></tr></table></body></html>',
  1
),
(
  'appointment_storno',
  'Termin storniert (Storno)',
  '<!doctype html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:24px;background:#fff1f2;font-family:Arial,Helvetica,sans-serif;color:#881337;"><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="640" style="max-width:640px;background:#ffffff;border:1px solid #fecdd3;border-radius:14px;overflow:hidden;"><tr><td style="padding:26px 30px;"><h1 style="margin:0 0 10px 0;font-size:26px;line-height:1.25;color:#9f1239;">Termin storniert</h1><p style="margin:0 0 14px 0;font-size:14px;line-height:1.6;color:#881337;">Hallo {{client.first_name}}, dein Termin wurde storniert.</p><div style="background:#fff1f2;border:1px solid #fecdd3;border-radius:10px;padding:14px;font-size:14px;line-height:1.7;color:#881337;"><strong>Termin:</strong> {{booking.scheduled_at}}<br><strong>Grund:</strong> {{booking.cancellation_reason}}</div></td></tr><tr><td style="padding:12px 30px;background:#fff1f2;border-top:1px solid #fecdd3;font-size:12px;color:#9f1239;">{{system.contact_email}}</td></tr></table></td></tr></table></body></html>',
  1
),
(
  'appointment_reschedule',
  'Termin umgebucht',
  '<!doctype html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:24px;background:#eff6ff;font-family:Arial,Helvetica,sans-serif;color:#1e3a8a;"><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="640" style="max-width:640px;background:#ffffff;border:1px solid #bfdbfe;border-radius:14px;overflow:hidden;"><tr><td style="padding:26px 30px;"><h1 style="margin:0 0 10px 0;font-size:26px;line-height:1.25;color:#1d4ed8;">Termin umgebucht</h1><p style="margin:0 0 14px 0;font-size:14px;line-height:1.6;color:#1e3a8a;">Hallo {{client.first_name}}, dein Termin wurde neu geplant.</p><div style="background:#eff6ff;border:1px solid #bfdbfe;border-radius:10px;padding:14px;font-size:14px;line-height:1.7;color:#1e3a8a;"><strong>Neuer Termin:</strong> {{booking.scheduled_at}}<br><strong>Dauer:</strong> {{booking.duration_minutes}} Minuten</div></td></tr><tr><td style="padding:12px 30px;background:#eff6ff;border-top:1px solid #bfdbfe;font-size:12px;color:#1d4ed8;">{{system.site_name}} | {{system.contact_email}}</td></tr></table></td></tr></table></body></html>',
  1
),
(
  'appointment_no_show',
  'Termin nicht wahrgenommen',
  'Hinweis zu deinem ausgefallenen Termin',
  '<!doctype html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:24px;background:#fff7ed;font-family:Arial,Helvetica,sans-serif;color:#7c2d12;"><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="640" style="max-width:640px;background:#ffffff;border:1px solid #fed7aa;border-radius:14px;overflow:hidden;"><tr><td style="padding:26px 30px;"><h1 style="margin:0 0 10px 0;font-size:26px;line-height:1.25;color:#9a3412;">Termin nicht wahrgenommen</h1><p style="margin:0 0 10px 0;font-size:14px;line-height:1.6;color:#7c2d12;">Wir konnten dich zu deinem Termin nicht erreichen.</p><p style="margin:0;font-size:14px;line-height:1.6;color:#7c2d12;">Bitte melde dich für eine neue Terminabstimmung.</p></td></tr><tr><td style="padding:12px 30px;background:#fff7ed;border-top:1px solid #fed7aa;font-size:12px;color:#9a3412;">{{system.support_email}}</td></tr></table></td></tr></table></body></html>',
  1
),
(
  'ticket_opened',
  'Ticket geoeffnet',
  'Dein Ticket ist jetzt in Bearbeitung',
  '<!doctype html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:24px;background:#f0f9ff;font-family:Arial,Helvetica,sans-serif;color:#0c4a6e;"><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="640" style="max-width:640px;background:#ffffff;border:1px solid #bae6fd;border-radius:14px;overflow:hidden;"><tr><td style="padding:26px 30px;"><h1 style="margin:0 0 10px 0;font-size:26px;line-height:1.25;color:#075985;">Ticket geoeffnet</h1><p style="margin:0 0 10px 0;font-size:14px;line-height:1.6;color:#0c4a6e;">Hallo {{client.first_name}}, dein Anliegen wird jetzt aktiv bearbeitet.</p><p style="margin:0;font-size:14px;line-height:1.6;color:#0c4a6e;">Bei Rueckfragen antworte einfach auf diese E-Mail.</p></td></tr><tr><td style="padding:12px 30px;background:#f0f9ff;border-top:1px solid #bae6fd;font-size:12px;color:#0369a1;">{{system.site_name}} | {{system.support_email}}</td></tr></table></td></tr></table></body></html>',
  1
),
(
  'ticket_closed',
  'Ticket abgeschlossen',
  'Dein Ticket wurde abgeschlossen',
  '<!doctype html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:24px;background:#f0fdfa;font-family:Arial,Helvetica,sans-serif;color:#134e4a;"><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="640" style="max-width:640px;background:#ffffff;border:1px solid #99f6e4;border-radius:14px;overflow:hidden;"><tr><td style="padding:26px 30px;"><h1 style="margin:0 0 10px 0;font-size:26px;line-height:1.25;color:#0f766e;">Ticket abgeschlossen</h1><p style="margin:0 0 10px 0;font-size:14px;line-height:1.6;color:#134e4a;">Hallo {{client.first_name}}, dein Ticket wurde als geloest markiert.</p><p style="margin:0;font-size:14px;line-height:1.6;color:#134e4a;">Falls noch etwas offen ist, antworte direkt auf diese Nachricht.</p></td></tr><tr><td style="padding:12px 30px;background:#f0fdfa;border-top:1px solid #99f6e4;font-size:12px;color:#0f766e;">{{system.support_email}}</td></tr></table></td></tr></table></body></html>',
  1
),
(
  'invoice_created',
  'Rechnung erstellt',
  'Deine Rechnung #{{invoice.invoice_number}}',
  '<!doctype html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:24px;background:#f4f4f5;font-family:Arial,Helvetica,sans-serif;color:#18181b;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td align="center"><table role="presentation" width="720" style="max-width:720px;background:#ffffff;border:1px solid #e4e4e7;border-radius:14px;overflow:hidden;"><tr><td style="padding:26px 32px 14px 32px;border-bottom:1px solid #e4e4e7;"><h1 style="margin:0 0 8px 0;font-size:26px;line-height:1.25;color:#18181b;">Rechnung #{{invoice.invoice_number}}</h1><p style="margin:0;font-size:14px;line-height:1.6;color:#3f3f46;">{{invoice.acceptance_message}}</p></td></tr><tr><td style="padding:24px 32px;"><table role="presentation" width="100%" style="background:#fafafa;border:1px solid #e4e4e7;border-radius:10px;"><tr><td style="padding:12px 14px;font-size:14px;line-height:1.6;color:#3f3f46;"><strong style="color:#18181b;">Rechnungsdatum:</strong> {{invoice.invoice_date}}<br><strong style="color:#18181b;">Faelligkeit:</strong> {{invoice.due_date}}<br><strong style="color:#18181b;">Betrag:</strong> {{invoice.total_amount}} {{invoice.currency_code}}<br><strong style="color:#18181b;">Status:</strong> {{invoice.status}}</td></tr></table><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin-top:16px;border-collapse:collapse;"><thead><tr><th align="left" style="padding:10px 0;border-bottom:1px solid #e4e4e7;font-size:13px;line-height:1.4;color:#52525b;">Position</th><th align="center" style="padding:10px 0;border-bottom:1px solid #e4e4e7;font-size:13px;line-height:1.4;color:#52525b;">Menge</th><th align="right" style="padding:10px 0;border-bottom:1px solid #e4e4e7;font-size:13px;line-height:1.4;color:#52525b;">Summe</th></tr></thead><tbody>{{invoice.items_html}}</tbody></table><table role="presentation" width="100%" style="margin-top:16px;background:#ffffff;border:1px solid #e4e4e7;border-radius:10px;"><tr><td style="padding:14px;font-size:14px;line-height:1.7;color:#3f3f46;"><strong style="color:#18181b;">Zahlungsinformationen</strong><div style="margin-top:10px;">{{payment.summary_html}}</div><p style="margin:10px 0 0 0;">{{invoice.payment_notice}}</p><p style="margin:8px 0 0 0;font-size:12px;color:#71717a;">{{invoice.tax_exemption_notice}}</p></td></tr></table></td></tr><tr><td style="padding:14px 32px;background:#fafafa;border-top:1px solid #e4e4e7;font-size:12px;line-height:1.5;color:#71717a;">{{system.site_name}} | {{system.contact_email}}</td></tr></table></td></tr></table></body></html>',
  1
),
(
  'payment_received',
  'Zahlung eingegangen',
  'Zahlung bestaetigt für Rechnung #{{invoice.invoice_number}}',
  '<!doctype html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:24px;background:#ecfdf5;font-family:Arial,Helvetica,sans-serif;color:#14532d;"><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="640" style="max-width:640px;background:#ffffff;border:1px solid #a7f3d0;border-radius:14px;overflow:hidden;"><tr><td style="padding:26px 30px;"><h1 style="margin:0 0 10px 0;font-size:26px;line-height:1.25;color:#14532d;">Zahlung eingegangen</h1><p style="margin:0 0 14px 0;font-size:14px;line-height:1.6;color:#14532d;">Vielen Dank, wir haben deine Zahlung erhalten.</p><div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:10px;padding:14px;font-size:14px;line-height:1.7;color:#14532d;"><strong>Rechnung:</strong> #{{invoice.invoice_number}}<br><strong>Betrag:</strong> {{invoice.total_amount}} {{invoice.currency_code}}<br><strong>Status:</strong> bezahlt</div></td></tr><tr><td style="padding:12px 30px;background:#f0fdf4;border-top:1px solid #bbf7d0;font-size:12px;color:#166534;">{{system.contact_email}}</td></tr></table></td></tr></table></body></html>',
  1
),
(
  'payment_reminder_1',
  'Zahlungserinnerung 1',
  'Freundliche Erinnerung: Rechnung #{{invoice.invoice_number}}',
  '<!doctype html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:24px;background:#fffbeb;font-family:Arial,Helvetica,sans-serif;color:#78350f;"><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="640" style="max-width:640px;background:#ffffff;border:1px solid #fde68a;border-radius:14px;overflow:hidden;"><tr><td style="padding:26px 30px;"><h1 style="margin:0 0 10px 0;font-size:26px;line-height:1.25;color:#92400e;">Freundliche Zahlungserinnerung</h1><p style="margin:0 0 10px 0;font-size:14px;line-height:1.6;color:#78350f;">Bitte begleiche die Rechnung #{{invoice.invoice_number}} bis zum Faelligkeitsdatum {{invoice.due_date}}.</p><p style="margin:0 0 14px 0;font-size:14px;line-height:1.6;color:#78350f;">Offener Betrag: <strong>{{invoice.total_amount}} {{invoice.currency_code}}</strong></p><div>{{payment.summary_html}}</div></td></tr><tr><td style="padding:12px 30px;background:#fffbeb;border-top:1px solid #fde68a;font-size:12px;color:#92400e;">{{system.support_email}}</td></tr></table></td></tr></table></body></html>',
  1
),
(
  'payment_reminder_2',
  'Zahlungserinnerung 2',
  'Letzte Erinnerung: Rechnung #{{invoice.invoice_number}}',
  '<!doctype html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:24px;background:#fff1f2;font-family:Arial,Helvetica,sans-serif;color:#881337;"><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="640" style="max-width:640px;background:#ffffff;border:1px solid #fecdd3;border-radius:14px;overflow:hidden;"><tr><td style="padding:26px 30px;"><h1 style="margin:0 0 10px 0;font-size:26px;line-height:1.25;color:#9f1239;">Letzte Zahlungserinnerung</h1><p style="margin:0 0 10px 0;font-size:14px;line-height:1.6;color:#881337;">Die Rechnung #{{invoice.invoice_number}} ist weiterhin offen.</p><p style="margin:0 0 14px 0;font-size:14px;line-height:1.6;color:#881337;">Bitte ueberweise <strong>{{invoice.total_amount}} {{invoice.currency_code}}</strong> umgehend.</p><div>{{payment.summary_html}}</div></td></tr><tr><td style="padding:12px 30px;background:#fff1f2;border-top:1px solid #fecdd3;font-size:12px;color:#9f1239;">Bei Rueckfragen: {{system.support_email}}</td></tr></table></td></tr></table></body></html>',
  1
)
ON DUPLICATE KEY UPDATE
  display_name = VALUES(display_name),
  subject_template = VALUES(subject_template),
  html_template = VALUES(html_template),
  is_active = VALUES(is_active),
  updated_at = CURRENT_TIMESTAMP;
