UPDATE email_templates
SET
  subject_template = 'Wir haben deine Anfrage erhalten - {{system.site_name}}',
  html_template = '<!doctype html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:24px;background:#f5f5f4;font-family:Arial,Helvetica,sans-serif;color:#1c1917;"><table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%"><tr><td align="center"><table role="presentation" cellspacing="0" cellpadding="0" border="0" width="680" style="max-width:680px;background:#ffffff;border:1px solid #e7e5e4;border-radius:14px;overflow:hidden;"><tr><td style="padding:28px 32px 14px 32px;border-bottom:1px solid #e7e5e4;"><div style="font-size:11px;letter-spacing:1.8px;text-transform:uppercase;color:#0f766e;font-weight:bold;">{{system.site_name}}</div><h1 style="margin:10px 0 8px 0;font-size:26px;line-height:1.25;color:#1c1917;">Danke für deine Anfrage</h1><p style="margin:0;font-size:14px;line-height:1.6;color:#57534e;">Hallo {{client.first_name}} {{client.last_name}}, wir haben deine Anfrage erfolgreich erhalten.</p></td></tr><tr><td style="padding:24px 32px;"><div style="background:#fafaf9;border:1px solid #e7e5e4;border-radius:10px;padding:16px;"><div style="font-size:12px;line-height:1.4;font-weight:bold;text-transform:uppercase;letter-spacing:0.6px;color:#44403c;">Anfragedetails</div><p style="margin:10px 0 0 0;font-size:14px;line-height:1.6;color:#44403c;"><strong>Anfrageart:</strong> {{request.type_label}}</p>{{request.customer_details_html}}</div><p style="margin:18px 0 0 0;font-size:14px;line-height:1.7;color:#44403c;">Wir melden uns zeitnah mit einem Terminvorschlag bei dir.</p></td></tr><tr><td style="padding:14px 32px;background:#fafaf9;border-top:1px solid #e7e5e4;font-size:12px;line-height:1.5;color:#57534e;">Support: {{system.support_email}} | Kontakt: {{system.contact_email}}</td></tr></table></td></tr></table></body></html>'
WHERE template_key = 'request_confirmation';

UPDATE email_templates
SET
  subject_template = 'Neue Anfrage eingegangen: {{client.first_name}} {{client.last_name}}',
  html_template = '<!doctype html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:24px;background:#f1f5f9;font-family:Arial,Helvetica,sans-serif;color:#0f172a;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td align="center"><table role="presentation" width="680" style="max-width:680px;background:#ffffff;border:1px solid #dbe3ec;border-radius:14px;overflow:hidden;"><tr><td style="padding:26px 32px 14px 32px;border-bottom:1px solid #e2e8f0;"><div style="font-size:11px;letter-spacing:1.8px;text-transform:uppercase;color:#3730a3;font-weight:bold;">Admin Notification</div><h1 style="margin:10px 0 8px 0;font-size:26px;line-height:1.25;color:#0f172a;">Neue Anfrage</h1><p style="margin:0;font-size:14px;line-height:1.6;color:#475569;">Eine neue Anfrage wurde ueber das Formular eingereicht.</p></td></tr><tr><td style="padding:22px 32px;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td valign="top" width="50%" style="padding-right:8px;"><div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:14px;"><div style="font-size:14px;font-weight:bold;color:#0f172a;">Kundendaten</div><p style="margin:10px 0 0 0;font-size:14px;line-height:1.6;color:#334155;">{{client.first_name}} {{client.last_name}}<br>{{client.email}}<br>{{client.phone}}</p></div></td><td valign="top" width="50%" style="padding-left:8px;"><div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:14px;"><div style="font-size:14px;font-weight:bold;color:#0f172a;">Anfrage</div><p style="margin:10px 0 8px 0;font-size:14px;line-height:1.6;color:#334155;"><strong>Anfrageart:</strong> {{request.type_label}}</p>{{request.admin_details_html}}</div></td></tr></table></td></tr><tr><td style="padding:14px 32px;background:#f8fafc;border-top:1px solid #e2e8f0;font-size:12px;line-height:1.5;color:#64748b;">Generiert: {{system.generated_at}}</td></tr></table></td></tr></table></body></html>'
WHERE template_key = 'admin_request_info';