CREATE TABLE projects (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `description` TEXT,
    `client_id` INT NOT NULL,
    `price_quote` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    `price_quote_ongoing` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    `final_price` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    `final_price_ongoing` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    `status` ENUM('pending', 'backlog', 'in_progress', 'review', 'completed', 'on_hold', 'cancelled') NOT NULL DEFAULT 'pending',
    `progress` INT NOT NULL DEFAULT 0,
    `system_tests_finished` BOOLEAN NOT NULL DEFAULT FALSE,
    `tested_by` INT NULL,
    `test_date` DATE NULL,
    `test_template` INT NULL,
    `test_data` JSON NULL,
    `due_date` DATE NOT NULL,
    `is_active` BOOLEAN NOT NULL DEFAULT TRUE,
    `deleted_at` TIMESTAMP NULL,
    `created_by` INT NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`client_id`) REFERENCES clients(id),
    FOREIGN KEY (`test_template`) REFERENCES form_templates(id),
    FOREIGN KEY (`created_by`) REFERENCES users(id),
    INDEX idx_project_id (`id`),
    INDEX idx_client_id (`client_id`)
);

CREATE TABLE project_phase (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `project_id` INT NOT NULL,
    `phase_name` VARCHAR(255) NOT NULL,
    `description` TEXT,
    `status` ENUM('pending', 'in_progress', 'review', 'completed', 'on_hold', 'cancelled') NOT NULL DEFAULT 'pending',
    `progress` INT NOT NULL DEFAULT 0,
    `integration_tests_finished` BOOLEAN NOT NULL DEFAULT FALSE,
    `tested_by` INT NULL,
    `test_date` DATE NULL,
    `test_template` INT NULL,
    `test_data` JSON NULL,
    `due_date` DATE NOT NULL,
    `deleted_at` TIMESTAMP NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`project_id`) REFERENCES projects(id),
    FOREIGN KEY (`test_template`) REFERENCES form_templates(id),
    INDEX idx_project_phase_id (`id`),
    INDEX idx_project_id (`project_id`)
);

CREATE TABLE project_members (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `project_id` INT NOT NULL,
    `user_id` INT NOT NULL,
    `role` ENUM('owner', 'manager', 'developer', 'designer', 'tester') NOT NULL DEFAULT 'developer',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`project_id`) REFERENCES projects(id),
    FOREIGN KEY (`user_id`) REFERENCES users(id),
    INDEX idx_project_member_id (`id`),
    INDEX idx_project_id (`project_id`),
    INDEX idx_user_id (`user_id`)
);